# Configuration SafeDep / vet scan
# Documentation des dépendances légitimes marquées comme suspectes

# Packages légitimes utilisés dans le projet
# Ces bibliothèques sont largement utilisées et maintenues

exceptions:
  # ebooklib - Bibliothèque Python pour manipuler les fichiers EPUB
  # GitHub: https://github.com/aerkalov/ebooklib
  # PyPI: ~200k téléchargements/mois
  # Utilisée pour: Extraction de texte depuis les ebooks EPUB
  - package: ebooklib
    version: "0.19"
    reason: "Bibliothèque standard pour traitement EPUB, dernière version stable"

  # Pillow - Fork PIL (Python Imaging Library)
  # GitHub: https://github.com/python-pillow/Pillow
  # PyPI: ~100M téléchargements/mois
  # Utilisée pour: Traitement d'images (dépendance de sentence-transformers)
  - package: pillow
    version: "12.0.0"
    reason: "Bibliothèque image standard Python, utilisée par ML frameworks"

  # Typer - CLI framework par le créateur de FastAPI
  # GitHub: https://github.com/tiangolo/typer
  # PyPI: ~50M téléchargements/mois
  # Utilisée pour: Interface CLI de ChromaDB
  - package: typer
    version: "0.19.2"
    reason: "Framework CLI moderne et sécurisé, dépendance de chromadb"

# Notes sur les vulnérabilités
security:
  # urllib3 - Mise à jour vers 2.5.0+ pour corriger CVE
  - package: urllib3
    minimum_version: "2.5.0"
    reason: "Correction de GHSA-48p4-8xcf-vxj5 (Medium severity)"
